name: Classroom Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        id: test
        run: pytest tests/ -v && echo "result=success" >> $GITHUB_OUTPUT || echo "result=fail" >> $GITHUB_OUTPUT
      - name: Set score
        run: |
          if [ "${{ steps.test.outputs.result }}" == "success" ]; then
            echo "TEST_RESULT=100" >> $GITHUB_ENV
          else
            echo "TEST_RESULT=0" >> $GITHUB_ENV
          fi